### ISSUE TITLE
Cannot install inside a fresh laravel 10 project

### ISSUE THREAD

**Issue by RRosalia** [TheDragonCode/laravel-actions#129]
### Environment

- PHP Version: 8.1
- Database Driver & Version: mysql 8.0
- Actions Version: ^4.2
- Laravel Version: 10

### Issue description

Composer install fails when installing inside a fresh laravel 10 project

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dragon-code/support[v6.0.1, ..., v6.11.0] require dragon-code/contracts ^2.18 -> found dragon-code/contracts[2.x-dev] but it does not match your minimum-stability.
    - dragon-code/laravel-actions dev-main requires dragon-code/support ^6.6 -> satisfiable by dragon-code/support[v6.6.0, ..., v6.11.0].
    - Root composer.json requires dragon-code/laravel-actions dev-main -> satisfiable by dragon-code/laravel-actions[dev-main].
```

### Steps to reproduce

1. Install Laravel 10
2. composer require dragon-code/laravel-actions

**Comment by andrey-helldar** [comment]
Check the value of the[ `minimum-stability`](https://laravel.com/docs/10.x/upgrade#updating-minimum-stability) key in the `composer.json`. I recommend replacing it with `stable` instead `dev`.

Due to the fact that your application is allowed to install DEV versions, the composer tries to download unstable versions of packages.

![image](https://user-images.githubusercontent.com/10347617/224977755-9fd21315-9b61-48ba-92e5-0ff86a332669.png)

**Comment by RRosalia** [comment]
Okay clear thanks! That was indeed the issue!

**Comment by andrey-helldar** [comment]
You're welcome!
